added imagenette_classes
probml/probml-data pull request #2
Opened 2021-06-11 13:24 UTC by always-newbie161

Added imagenette_names as a CSV file

2021-06-11 15:10 UTC, mjsML requested changes
I'm wondering why we should have those? Isn't this part of the TFDS data?

2021-06-15 17:02 UTC, murphyk requested changes

2021-06-15 17:02 UTC, murphyk commented on data/imagenette_class_names.csv
> +1,English springler
typo: springer

2021-06-15 17:02 UTC, murphyk commented on data/imagenette_class_names.csv
> +2,casette_player
typo: cassette

2021-06-15 17:02 UTC, murphyk commented on data/imagenette_class_names.csv
> +label,name
Please be consistent with capitalization, and use of underscores to join words.

2021-06-15 17:09 UTC, murphyk requested changes
you are still inconsistent with capitalization.
I suggest lower case for everything.

2021-06-15 17:23 UTC, merged